name: tia_pemmob2
description: A new Flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  path: ^1.8.1
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  share_plus: ^10.1.2
  open_file: ^3.5.10

  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/iconhome.jpg
    - assets/bg1.jpg
    - assets/bg2.jpg
    - assets/pp1.png
